server:
  port: 8040
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yapi?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: Root1234
    type: com.zaxxer.hikari.HikariDataSource
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    suffix: .html
    prefix: classpath:/templates/
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  notEmpty: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.ifs.yapi.entity
  configuration:
    map-underscore-to-camel-case: true